name: Theming Request
description: Wouldn't it be nice if Clarity Noir could...
body:
  - type: textarea
    attributes:
      label: Description
      description: What do you want Clarity Noir to do, and why?
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Want to help?
      description: |
        Contributions are greatly appreciated!
      options:
        - label: I would like to work on this and submit a PR with my changes.
          required: false
