name: Prerelease

on:
  release:
    types:
      - prereleased

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Configure Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Configure cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install packages
        run: npm ci

      - name: Publish prerelease version of extension
        run: npx vsce publish --pre-release -p $VSCE_TOKEN
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
